## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

# Hypothesis

We hypothesize that broadband internet access is positively associated with employment status and annual earnings among U.S. adults aged 25–54. Individuals with household broadband subscriptions are expected tohave better labor-market outcomes, as internet connectivity facilitates job search, remote work, and access to employment opportunities.

## Data

### Data overview

In [9]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [10]:
# Setup code -- Run only once after cloning!!! 
#
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading airline-safety.csv:   0%|          | 0.00/1.23k [00:00<?, ?B/s]

Successfully downloaded: airline-safety.csv

Downloading bad-drivers.csv:   0%|          | 0.00/1.37k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00, 21.40it/s]

Successfully downloaded: bad-drivers.csv

### Dataset #1 

   
   Dataset Name: Current Population Survey (CPS) Basic Monthly Data
   
   Link to the dataset: https://www.census.gov/data/datasets/time-series/demo/cps/cps-basic.html

   Number of observations: 1,000 individuals.

   Number of variables: 9 variables used in this project.
   
   Relevant variables:
   - Employment status
   - Annual earnings
   - Education level
   - Household broadband subscription
   - Age, gender, and race
   
  Shortcomings: The dataset is survey based and may contain self-report bias. Some broadband-related variables are only available in supplements, which may limit temporal consistency.

In [36]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/00-raw/jan26pub1.csv")
df.columns = df.columns.str.strip().str.lower()

print(df.columns)

cps_vars = [
    "prtage",
    "pemlr",
    "pternwa",
    "peeduca",
    "pesex",
    "pemaritl",
    "ptdtrace",
    "peio1icd",
    "pwcmpwgt"
]

df = df[cps_vars].copy()
df = df.rename(columns={
    "prtage": "age",
    "pemlr": "labor_force_status",
    "pternwa": "weekly_earnings_raw",
    "peeduca": "education_level",
    "pesex": "sex",
    "pemaritl": "marital_status",
    "ptdtrace": "race",
    "peio1icd": "industry_code",
    "pwcmpwgt": "survey_weight_raw"
})
df.head()

Index(['hrhhid2', 'hufinal', 'occurnum', 'huinttyp', 'hurespli', 'huprscnt',
       'hutypea', 'hutypb', 'hutypc', 'hubus',
       ...
       'ptot', 'ptwk', 'pthr', 'gtcbsa', 'gtco', 'gtcbsast', 'gtcbsasz',
       'gtcsa', 'gtmetsta', 'gtindvpc'],
      dtype='object', length=393)

,age,labor_force_status,weekly_earnings_raw,education_level,sex,marital_status,race,industry_code,survey_weight_raw
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62.0,6.0,-1.0,34.0,1.0,6.0,2.0,7770.0,26617171.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,73.0,5.0,-1.0,37.0,1.0,1.0,1.0,-1.0,13344086.0
4,73.0,5.0,-1.0,40.0,2.0,1.0,1.0,-1.0,18191075.0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  719 non-null    float64
 1   labor_force_status   719 non-null    float64
 2   weekly_earnings_raw  719 non-null    float64
 3   education_level      719 non-null    float64
 4   sex                  719 non-null    float64
 5   marital_status       719 non-null    float64
 6   race                 719 non-null    float64
 7   industry_code        719 non-null    float64
 8   survey_weight_raw    719 non-null    float64
dtypes: float64(9)
memory usage: 70.4 KB

In [38]:
df.describe()

,age,labor_force_status,weekly_earnings_raw,education_level,sex,marital_status,race,industry_code,survey_weight_raw
count,719.000000,719.000000,7.190000e+02,719.000000,719.000000,719.000000,719.000000,719.000000,7.190000e+02
mean,47.435327,2.781641,1.890292e+04,36.311544,1.520167,2.638387,1.435327,3104.296245,2.743424e+07
std,23.584812,2.552163,1.005427e+05,13.350441,0.499941,2.402407,1.440918,3706.444906,2.026919e+07
min,0.000000,-1.000000,-1.000000e+00,-1.000000,1.000000,-1.000000,1.000000,-1.000000,0.000000e+00
25%,28.000000,1.000000,-1.000000e+00,39.000000,1.000000,1.000000,1.000000,-1.000000,7.559951e+06
50%,51.000000,1.000000,-1.000000e+00,40.000000,2.000000,1.000000,1.000000,-1.000000,2.904696e+07
75%,67.000000,5.000000,-1.000000e+00,43.000000,2.000000,6.000000,1.000000,7330.000000,4.109602e+07
max,85.000000,7.000000,1.091850e+06,46.000000,2.000000,6.000000,16.000000,9590.000000,9.836383e+07

In [39]:
df.isnull().sum()

age                    281
labor_force_status     281
weekly_earnings_raw    281
education_level        281
sex                    281
marital_status         281
race                   281
industry_code          281
survey_weight_raw      281
dtype: int64

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them